### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by Sam44323** [invariant-labs/protocol#260]
Hey team, the [protocol-gamma.vercel.app](http://protocol-gamma.vercel.app/) is down!
<img width="962" alt="Screenshot 2022-09-12 at 10 51 32 PM" src="https://user-images.githubusercontent.com/65643151/189717043-43399469-45be-461a-96a2-1c0f932c4a95.png">

**Comment by wojciech-cichocki** [comment]
solved
